### ISSUE TITLE
Add logfile.

### ISSUE THREAD

**Issue by 9600** [DesignSparkRS/aq-device#12]
By default the application should log:

* info messages to /aq/log/aq.log
* errors to /aq/log/error.log

With the option to configure this via a key called 'logging' under [esdk] in aq.toml, where a value of:

* 'error' logs errors only
* 'false' disables logging altogether

**Comment by callumsnowden** [comment]
I propose we use `full`, `error` and `off` for possible logging values as this makes implementation easier, and the application can then default to `full` if the `logging` key isn't present in the configuration file.
