### ISSUE TITLE
PrometheusWriter formatting errors.

### ISSUE THREAD

**Issue by 9600** [DesignSparkRS/aq-device#15]
### Software versions

DesignSpark.ESDK 0.0.4
aq-device commit 946d84bb1fdd63d531def5ca7a6888647f6e294d

###  Errors

Mar 21 19:01:59 airquality python3[497]: 2022-03-21 19:01:59,826 [ERROR] PrometheusWriter prometheusUpdateThread_aqpublic: Could not format data, reason 'instance'
Mar 21 19:01:59 airquality python3[497]: 2022-03-21 19:01:59,864 [ERROR] PrometheusWriter prometheusUpdateThread_private: Could not format data, reason 'instance'
Mar 21 19:01:59 airquality python3[497]: 2022-03-21 19:01:59,864 [ERROR] PrometheusWriter prometheusUpdateThread_private: Could not format data, reason 'instance'
Mar 21 19:06:59 airquality python3[497]: 2022-03-21 19:06:59,930 [ERROR] PrometheusWriter prometheusUpdateThread_aqpublic: Could not format data, reason 'instance'
Mar 21 19:06:59 airquality python3[497]: 2022-03-21 19:06:59,964 [ERROR] PrometheusWriter prometheusUpdateThread_private: Could not format data, reason 'instance'
Mar 21 19:06:59 airquality python3[497]: 2022-03-21 19:06:59,964 [ERROR] PrometheusWriter prometheusUpdateThread_private: Could not format data, reason 'instance'
Mar 21 19:12:00 airquality python3[497]: 2022-03-21 19:12:00,040 [ERROR] PrometheusWriter prometheusUpdateThread_aqpublic: Could not format data, reason 'instance'
Mar 21 19:12:00 airquality python3[497]: 2022-03-21 19:12:00,040 [ERROR] PrometheusWriter prometheusUpdateThread_aqpublic: Could not format data, reason 'instance'
Mar 21 19:12:00 airquality python3[497]: 2022-03-21 19:12:00,062 [ERROR] PrometheusWriter prometheusUpdateThread_private: Could not format data, reason 'instance'
Mar 21 19:12:00 airquality python3[497]: 2022-03-21 19:12:00,062 [ERROR] PrometheusWriter prometheusUpdateThread_private: Could not format data, reason 'instance'

**Comment by callumsnowden** [comment]
Incorrect key names in config file, issue #16 has been opened in response to this.
