### ISSUE TITLE
Add a debug screen to the local display.

### ISSUE THREAD

**Issue by 9600** [DesignSparkRS/aq-device#20]
Add a 2nd screen to the local display that you swipe to with:

* Software versions
* GPS status (lock and number of sats)
* Free space on /aq filesystem
* CSV logging status
* App logging status (debug enabled)
* Prometheus endpoint status
  * We can have multiple endpoints, so not sure how best to implement this. Could just be two counters, for success and fail? Or create    a line for each endpoint with the label (part after the "." in config) and time of the last successful post to this?

**Comment by callumsnowden** [comment]
Implemented in 6715c8675ea1a324b2bfd513202fa53c4122f7af

Long press takes a user into a debugging screen, from which a short press moves to the next debugging screen, and then one final long press returns to the home screen.
