### ISSUE TITLE
Add support for new sensors.

### ISSUE THREAD

**Issue by 9600** [DesignSparkRS/aq-device#24]
Add support for:

- [x] ESDK-NO2
- [x] ESDK-NRD
- [x] ESDK-FDH

See also dependencies DesignSparkRS/DesignSpark.ESDK#4, DesignSparkRS/DesignSpark.ESDK#5 and DesignSparkRS/DesignSpark.ESDK#6.

**Comment by callumsnowden** [comment]
NRD support implemented, need to test against hardware.

**Comment by callumsnowden** [comment]
Support for new sensors implemented in UI in https://github.com/DesignSparkRS/aq-device/commit/28fb262154b9d9ec333e04135587ce9d56483e87
